config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
    

  devise_scope :user do
    get "users/menu" => "users/registrations#menu"
    get "users/sign_up/credit" => "users/registrations#credit"
    get "users/sign_up/confirmation" => "users/registrations#confirmation"
    get "users/sign_in/manu" => "users/sessions#menu"
  end

  resources :teams, only:[:index, :show]

  resources :schedules, only:[:index, :show]
  
  resources :stocks, only: [:index, :show] do
    resources :orders
  end

  resources :venues, only: [:index, :show]

  resources :users, only: [:show] do
    member do
      get 'ticket', to: 'users#ticket'
      get 'credit', to: 'users#credit'
    end
  end


  root to: "teams#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable,omniauth_providers: [:google_oauth2]

  has_many :cards
  has_many :orders
  has_many :tickets
  has_many :sns_credentials, dependent: :destroy

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      else
        user = User.create(
          name: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20],
          )
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      end
    end
    return user
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    callback_for(:google)
  end
  
  def callback_for(provider)
    @user = User.find_oauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication
      set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
    else
      session["devise.#{provider}_data"] = request.env["omniauth.auth"].except("extra")
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path and return
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  require "payjp"

  def menu
  end

  def new
    @user = User.new
    session[:user] = @user
  end

  def credit
    session[:user] = user_params
    @user = User.new(user_params)
  end

  def confirmation
    Payjp.api_key = Rails.application.credentials.dig(:payjp, :PAYJP_SECRET_KEY)

    if params[:payjpToken].present?
      @customer = Payjp::Customer.create(
        description: 'TicketShop',
        card: params[:payjpToken],
      )
    else
      render :credit
      return
    end

    @user = User.new(session[:user])
    @user.cards.build(
      user_id:        @user.id,
      customer_id:    @customer.id,
      card_id:        @customer.default_card,
    )

    if @user.save!
      user = @user
      session.clear
      session[:id] = @user.id
      sign_in User.find(session[:id]) unless user_signed_in?
    else
      redirect_to root_path
    end
  end



  private
  def user_params
    params.require(:user).permit(
      :name,
      :name_kana,
      :email,
      :password,
      :password_confirmation
    )
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def ticket
    @tickets = Ticket.where(user_id: current_user.id).includes(:schedule)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved",                 |
        count: resource.errors.count,                       |
        resource: resource.class.model_name.human.downcase) |
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_header_user.html.haml
.header-user
  =link_to root_path, class:"header-user__logo" do
    TICKETSHOP

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/

app/views/users/shared/_signin-form.html.haml
.signin-form
  %h2.signin-form__title
    ログイン
  .signin-form__inner
    = form_with model: @user, url: new_user_session_path, id: 'new_user', class: 'signin-user', local: true do |f|
      .signin-user__mail
        .form-group
          .form-group__text
            %label メールアドレス
            %span.form-group__text--red 必須
          .form-group__input
            =f.email_field :email, class: "form-control", placeholder: "例) xxx@example.com",  autocomplete: "email"
      .signin-user__mail
        .form-group
          .form-group__text
            %label パスワード
            %span.form-group__text--red 必須
          .form-group__input
            = f.password_field :password, autocomplete: "password", class: "form-control", placeholder: "例) 6文字以上の英数字"
      .signin-user__button
        =f.submit "ログイン", class:"btn btn-primary btn-lg"

app/views/users/shared/_signin-menu.html.haml
.signin-form
  %h2.signin-form__title
    ログイン
  .signin-form__inner
    .signin-menu
      .signin-menu__mail
        = link_to new_user_session_path do
          %span メールアドレスでログイン
      .signin-menu__google
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post do
          %span Googleアカウントでログイン

app/views/users/shared/_signup-confirmation.html.haml
.signup-form
  %h2.signup-form__title 登録完了
  .signup-form__inner
    .signup-confirmation
      .signup-confirmation__text
        新規登録完了しました。
      .signup-confirmation__button
        =link_to root_path do
          %span.btn.btn-primary.btn-lg
            トップページへ

app/views/users/shared/_signup-credit.html.haml
.signup-form
  %h2.signup-form__title
    クレジットカード登録
  .signup-form__inner
    = form_with url:users_sign_up_confirmation_path, method: :get, id:'credit-form', class: 'signup-credit', local:true do |f|
      .signup-credit__number
        .form-group
          .form-group__text
            %label カード番号
            %span.form-group__text--red 必須
          .form-group__input
            %input{id:'credit_number', name:'credit_number', class:'form-control', type:'text'}
      .signup-credit__limit
        .form-group
          .form-group__text
            %label 有効期限
            %span.form-group__text--red 必須
          .form-group__input--limit
            %select{id:'exp_month', name:'exp_month', class:'form-control', type:'text'}
              = ('01'..'12').each do |month|
                %option{value: month}
                  = month
            %span 月
            %select{id:'exp_year', name:'exp_yaer', class:'form-control', type:'text'}
              = (20..30).each do |year|
                - four_year = '20' + year.to_s
                %option{value: four_year}
                  = year
            %span 年
      .signup-credit__cvc
        .form-group
          .form-group__text
            %label セキュリティコード
            %span.form-group__text--red 必須
          .form-group__input--cvc
            %input{id:'credit_code', class:'form-control', type:'text'}
      .signup-credit__button
        %button.btn.btn-primary.btn-lg#token_submit{type:'submit'} 完了

app/views/users/shared/_signup-form.html.haml
.signup-form
  %h2.signup-form__title
    新規登録
  .signup-form__inner
    = form_with model: @user, url: users_sign_up_credit_path, method: :get, id: 'new_user', class: 'signup-user', local: true do |f|
      .signup-user__name
        .form-group
          .form-group__text
            %label 氏名
            %span.form-group__text--red 必須
          .form-group__input
            = f.text_field :name, autocomplete: "name", class: "form-control", placeholder: "例) 太郎"
      .signup-user__name-kana
        .form-group
          .form-group__text
            %label 氏名(カナ)
            %span.form-group__text--red 必須
          .form-group__input
            = f.text_field :name_kana, autocomplete: "name_kana", class: "form-control", placeholder: "例) タロウ"
      .signup-user__mail
        .form-group
          .form-group__text
            %label メールアドレス
            %span.form-group__text--red 必須
          .form-group__input
            =f.email_field :email, class: "form-control", placeholder: "例) xxx@example.com",  autocomplete: "email"
      .signup-user__password
        .form-group
          .form-group__text
            %label パスワード
            %span.form-group__text--red 必須
          .form-group__input
            = f.password_field :password, autocomplete: "password", class: "form-control", placeholder: "例) 6文字以上の英数字"
      .signup-user__password
        .form-group
          .form-group__text
            %label パスワード再確認
            %span.form-group__text--red 必須
          .form-group__input
            = f.password_field :password, autocomplete: "password", class: "form-control", placeholder: "例) 6文字以上の英数字"
      .signup-user__button
        =f.submit "クレジットカード登録", class:"btn btn-primary btn-lg"

app/views/users/shared/_signup-menu.html.haml
.signup-form
  %h2.signup-form__title
    新規登録
  .signup-form__inner
    .signup-menu
      .signup-menu__mail
        = link_to new_user_registration_path do
          %span メールアドレスで登録
      .signup-menu__twitter
        = link_to user_google_oauth2_omniauth_authorize_path, method: :post do
          %span Googleアカウントで登録

app/views/users/shared/_user-mypage.html.haml
.mypage-main
  %h2.mypage-main__title
    ユーザーページ
  .mypage-main__inner
    -user = current_user.name
    %p.inner-text ようこそ！ #{user}
    .user-menu
      = link_to "", remote: true do
        ユーザー情報確認
      = link_to ticket_user_path do
        チケット一覧
      = link_to credit_user_path do
        クレジットカード追加