config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
    

  devise_scope :user do
    get "users/menu" => "users/registrations#menu"
    get "users/sign_up/credit" => "users/registrations#credit"
    get "users/sign_up/confirmation" => "users/registrations#confirmation"
    get "users/sign_in/manu" => "users/sessions#menu"
  end

  resources :teams, only:[:index, :show]

  resources :schedules, only:[:index, :show]
  
  resources :stocks, only: [:index, :show] do
    resources :orders
  end

  resources :venues, only: [:index, :show]

  resources :users, only: [:show] do
    member do
      get 'ticket', to: 'users#ticket'
      get 'credit', to: 'users#credit'
    end
  end


  root to: "teams#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :stock

  has_many :tickets
  accepts_nested_attributes_for :tickets
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  def start_time
    self.match_date
  end

  has_many :stocks
  has_many :tickets


  belongs_to :venue
  belongs_to :team1, class_name: 'Team', foreign_key: 'team1_id'
  belongs_to :team2, class_name: 'Team', foreign_key: 'team2_id'
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/stadium.rb
class Stadium < ApplicationRecord
  mount_uploader :image, ImageUploader



end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :schedule
  
  has_many :orders
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team1_schedules, class_name: 'Schedule', foreign_key: 'team1_id'
  has_many :team2_schedules, class_name: 'Schedule', foreign_key: 'team2_id'
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :order
  belongs_to :schedule


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable,omniauth_providers: [:google_oauth2]

  has_many :cards
  has_many :orders
  has_many :tickets
  has_many :sns_credentials, dependent: :destroy

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      else
        user = User.create(
          name: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20],
          )
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      end
    end
    return user
  end

end

app/models/venue.rb
class Venue < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :schedules
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_stock, only: [:index,:new]

  def index
    @order = Order.new
    @order.tickets.build
  end

  def create
    @order = Order.new(order_params)
    @order.save!
      redirect_to root_path
  end

  private
  def order_params
    params.require(:order).permit(:count, tickets_attributes: [:id,:grade,:price,:user_id,:schedule_id]).merge(user_id: current_user.id, stock_id: params[:stock_id])
  end

  def set_stock
    @stock = Stock.find(params[:stock_id])
  end

end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController


  def index
    @schedules = Schedule.all.includes(:team1, :team2)

  end

  def show
    @schedule = Schedule.find(params[:id])
    @stocks = Stock.where(schedule_id:[params[:id]])
  end

end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @schedules = Schedule.includes(:team1, :team2).where(team1_id:[params[:id]]).or (Schedule.includes(:team1, :team2).where(team2_id:[params[:id]]))
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def ticket
    @tickets = Ticket.where(user_id: current_user.id).includes(:schedule)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/schedules/index.html.haml
.schedule-wrapper
  = render "shared/header-main"
  .schedule-main
    .schedule-inner
      %section.schedule-inner__month
        %h2.TeamSchedule-inner__month--title
          今月のスケジュール
        = month_calendar events: @schedules do |date, schedules|
          =date.day
          - schedules.each do |schedule|
            .match-name
              =link_to schedule_path(schedule) do
                = schedule.team1.name
                %span VS
                = schedule.team2.name
  = render "shared/footer-main"

app/views/schedules/show.html.haml
.schedule-wrapper
  = render "shared/header-main"
  .schedule-details
    .schedule-details__inner
      .match-index
        .match-index__date
          = @schedule.match_date.strftime('%m月 %d日')
        .match-index__time
          = @schedule.match_date.strftime('%H:%M')
          開始
        .match-index__stadium
          会場
          = @schedule.venue.name
      .match-title
        %span
          = @schedule.team1.name
        %span VS
        %span
          = @schedule.team2.name
      .match-ticket
        - @stocks.each do |stock|
          .match-ticket__inner
            .match-ticket__inner--upr
              .ticket-grade
                = stock.grade
              .ticket-price
                =stock.price
                円
            .match-ticket__inner--lwr
              =link_to stock_orders_path(stock) do
                枚数を選ぶ
      .stock
        = link_to "" do
          在庫管理

= render "shared/footer-main"