config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
    

  devise_scope :user do
    get "users/menu" => "users/registrations#menu"
    get "users/sign_up/credit" => "users/registrations#credit"
    get "users/sign_up/confirmation" => "users/registrations#confirmation"
    get "users/sign_in/manu" => "users/sessions#menu"
  end

  resources :teams, only:[:index, :show]

  resources :schedules, only:[:index, :show]
  
  resources :stocks, only: [:index, :show] do
    resources :orders
  end

  resources :venues, only: [:index, :show]

  resources :users, only: [:show] do
    member do
      get 'ticket', to: 'users#ticket'
      get 'credit', to: 'users#credit'
    end
  end


  root to: "teams#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  belongs_to :stock

  has_many :tickets
  accepts_nested_attributes_for :tickets
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  def start_time
    self.match_date
  end

  has_many :stocks
  has_many :tickets


  belongs_to :venue
  belongs_to :team1, class_name: 'Team', foreign_key: 'team1_id'
  belongs_to :team2, class_name: 'Team', foreign_key: 'team2_id'
end

app/models/sns_credential.rb
class SnsCredential < ApplicationRecord
  belongs_to :user
end

app/models/stadium.rb
class Stadium < ApplicationRecord
  mount_uploader :image, ImageUploader



end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :schedule
  
  has_many :orders
end

app/models/team.rb
class Team < ApplicationRecord
  has_many :team1_schedules, class_name: 'Schedule', foreign_key: 'team1_id'
  has_many :team2_schedules, class_name: 'Schedule', foreign_key: 'team2_id'
end

app/models/ticket.rb
class Ticket < ApplicationRecord

  belongs_to :order
  belongs_to :schedule


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable,omniauth_providers: [:google_oauth2]

  has_many :cards
  has_many :orders
  has_many :tickets
  has_many :sns_credentials, dependent: :destroy

  def self.find_oauth(auth)
    uid = auth.uid
    provider = auth.provider
    snscredential = SnsCredential.where(uid: uid, provider: provider).first
    if snscredential.present?
      user = User.where(id: snscredential.user_id).first
    else
      user = User.where(email: auth.info.email).first
      if user.present?
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      else
        user = User.create(
          name: auth.info.name,
          email:    auth.info.email,
          password: Devise.friendly_token[0, 20],
          )
        SnsCredential.create(
          uid: uid,
          provider: provider,
          user_id: user.id
          )
      end
    end
    return user
  end

end

app/models/venue.rb
class Venue < ApplicationRecord
  mount_uploader :image, ImageUploader

  has_many :schedules
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def index
    @teams = Team.all
  end

  def show
    @team = Team.find(params[:id])
    @schedules = Schedule.includes(:team1, :team2).where(team1_id:[params[:id]]).or (Schedule.includes(:team1, :team2).where(team2_id:[params[:id]]))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper

end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    = favicon_link_tag()
    %title Ticketshop
    %script{src: "https://js.pay.jp/", type: "text/javascript"}
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body
    = yield

app/views/shared/_footer-main.html.haml
%footer.footer-main
  .footer-main__text
    %p 2020 MASAHIDEーHIGASHI

app/views/shared/_header-main.html.haml
%header.header-main
  .header-inner
    .inner-upr
      =link_to root_path, class:"inner-upr__logo" do
        TICKETSHOP
      .inner-upr__userbox
        -if user_signed_in?
          .inner-upr__userbox--mypage
            =link_to user_path(current_user.id), class:"inner-upr__userbox--link" do
              マイページ
          .inner-upr__userbox--logout
            =link_to destroy_user_session_path, method: :delete, class:"inner-upr__userbox--link" do
              ログアウト
        -else
          .inner-upr__userbox--new
            =link_to users_menu_path, class: "inner-upr__userbox--link" do
              %span.font-red 新規登録
          .inner-upr__userbox--login
            =link_to users_sign_in_manu_path, class: "inner-upr__userbox--link" do
              %span ログイン

    .inner-lwr
      .inner-lwr__link
        =link_to schedules_path, class: "inner-lwr__link--schedule" do
          =icon('far', 'calendar-alt',class:"icon-header")
          %span スケジュール一覧
        =link_to venues_path, class: "inner-lwr__link--venue" do
          =icon('fas', 'drum-steelpan',class:"icon-header")
          %span スタジアム一覧